import { useMemo, useState } from "react";
import { Bell, CheckCheck, History, KeyRound, LogIn, Monitor, Save, ShieldAlert, ShieldCheck, Timer } from "lucide-react";
import type { Settings } from "../data";
import { fmtDateTime, useAdmin } from "../store";
import { Button, DemoTag, EmptyState, Field, FilterBar, Forbidden, PageHeader, Panel, SearchInput, Select, StatusBadge, Tabs, Toggle, inputCls } from "../ui";
import { cn } from "../../utils/cn";

/* ─────────── Notifications ─────────── */

const noticeTypes = ["All", "System", "Security", "Orders", "Inventory", "Users", "Infrastructure"];

export function NotificationsPage() {
  const { data, mutate, can } = useAdmin();
  const [tab, setTab] = useState("All");
  const [unreadOnly, setUnreadOnly] = useState(false);
  if (!can("notifications.view")) return <Forbidden permission="notifications.view" />;
  const rows = data.notifications.filter((n) => (tab === "All" || n.type === tab) && (!unreadOnly || !n.read));
  const unread = data.notifications.filter((n) => !n.read).length;
  return (
    <>
      <PageHeader eyebrow="System" title="Notifications" description="Alerts generated by the Control Center. For example, inventory adjustments that drop below minimum stock."
        breadcrumbs={[{ label: "Overview", to: "/admin" }, { label: "Notifications" }]}
        actions={unread > 0 && <Button icon={CheckCheck} onClick={() => mutate("notifications", (l) => l.map((n) => ({ ...n, read: true })))}>Mark all as read</Button>} />
      <Panel padded={false}>
        <div className="flex flex-col gap-2 px-3 pt-1 sm:flex-row sm:items-center sm:justify-between">
          <Tabs tabs={noticeTypes} value={tab} onChange={setTab} />
          <label className="flex items-center gap-2 px-2 py-2 text-xs text-steel"><input type="checkbox" checked={unreadOnly} onChange={(e) => setUnreadOnly(e.target.checked)} className="accent-[#0066FF]" />Unread only</label>
        </div>
        {rows.length ? (
          <ul className="divide-y divide-white/[0.05]">
            {rows.map((n) => (
              <li key={n.id} className={cn("flex items-start gap-4 px-5 py-4", !n.read && "bg-hn/[0.12]")}>
                <span className={cn("mt-1.5 h-2 w-2 shrink-0 rounded-full", n.read ? "border border-steel/50" : "bg-volt")} aria-hidden />
                <div className="min-w-0 flex-1">
                  <p className="text-sm text-snow/90">{n.title}</p>
                  <p className="mt-1 flex flex-wrap items-center gap-2 text-[11px] text-steel"><span className="font-mono uppercase tracking-[0.1em]">{n.type}</span>·<time dateTime={n.date}>{fmtDateTime(n.date)}</time>·<span>{n.read ? "Read" : "Unread"}</span></p>
                </div>
                <Button size="sm" variant="ghost" onClick={() => mutate("notifications", (l) => l.map((x) => x.id === n.id ? { ...x, read: !x.read } : x))}>{n.read ? "Mark unread" : "Mark read"}</Button>
              </li>
            ))}
          </ul>
        ) : <EmptyState icon={Bell} title="No notifications." description="You're all caught up. New system, security, order and inventory alerts will appear here." />}
      </Panel>
    </>
  );
}

/* ─────────── Activity log ─────────── */

const DAY = 86400000;

export function ActivityPage() {
  const { data, can } = useAdmin();
  const [user, setUser] = useState("all");
  const [module, setModule] = useState("all");
  const [range, setRange] = useState("all");
  const [q, setQ] = useState("");
  const actors = [...new Set(data.activity.map((a) => a.actor))];
  const modules = [...new Set(data.activity.map((a) => a.module))];
  const rows = useMemo(() => data.activity.filter((a) =>
    (user === "all" || a.actor === user) && (module === "all" || a.module === module) &&
    (range === "all" || Date.now() - new Date(a.date).getTime() <= Number(range) * DAY) &&
    (!q || `${a.action} ${a.target}`.toLowerCase().includes(q.toLowerCase()))), [data.activity, user, module, range, q]);
  if (!can("activity.view")) return <Forbidden permission="activity.view" />;

  const groups = rows.reduce<Record<string, typeof rows>>((acc, a) => {
    const key = new Intl.DateTimeFormat("en-US", { weekday: "long", month: "short", day: "numeric", year: "numeric" }).format(new Date(a.date));
    (acc[key] ||= []).push(a);
    return acc;
  }, {});

  return (
    <>
      <PageHeader eyebrow="System" title="Activity Log" description="Audit trail of administrative actions. Entries from this session are tagged; sample entries are marked DEMO."
        breadcrumbs={[{ label: "Overview", to: "/admin" }, { label: "Activity Log" }]} />
      <Panel padded={false}>
        <FilterBar>
          <SearchInput value={q} onChange={setQ} placeholder="Search action or target" label="Search activity" />
          <Select label="User" value={user} onChange={setUser} options={[{ value: "all", label: "All users" }, ...actors]} className="sm:w-44" />
          <Select label="Module" value={module} onChange={setModule} options={[{ value: "all", label: "All modules" }, ...modules]} className="sm:w-40" />
          <Select label="Date" value={range} onChange={setRange} options={[{ value: "all", label: "Any date" }, { value: "1", label: "Last 24 hours" }, { value: "7", label: "Last 7 days" }, { value: "30", label: "Last 30 days" }]} className="sm:w-40" />
        </FilterBar>
        {rows.length ? (
          <div className="p-5">
            {Object.entries(groups).map(([day, items]) => (
              <section key={day} className="mb-6 last:mb-0">
                <h2 className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-steel">{day}</h2>
                <ol className="space-y-2">
                  {items.map((a) => (
                    <li key={a.id} className="grid gap-3 rounded-lg border border-white/[0.06] bg-obsidian/40 p-4 sm:grid-cols-[1.1fr_1.1fr_1.3fr_auto] sm:items-center">
                      {[["Administrator", a.actor], ["Action", a.action], [a.module, a.target]].map(([k, v]) => (
                        <div key={k} className="min-w-0">
                          <div className="font-mono text-[9.5px] uppercase tracking-[0.16em] text-steel/80">{k}</div>
                          <div className="mt-0.5 truncate text-sm font-medium text-snow">{v}</div>
                        </div>
                      ))}
                      <div className="flex items-center gap-2 sm:flex-col sm:items-end">
                        <time dateTime={a.date} className="font-mono text-[11px] text-steel">{new Intl.DateTimeFormat("en-US", { hour: "2-digit", minute: "2-digit" }).format(new Date(a.date))}</time>
                        {a.demo ? <DemoTag /> : <span className="rounded border border-tech/40 px-1.5 font-mono text-[9px] uppercase tracking-[0.12em] text-[#9cc6ff]">This session</span>}
                      </div>
                    </li>
                  ))}
                </ol>
              </section>
            ))}
          </div>
        ) : <EmptyState icon={History} title="No activity matches these filters." />}
      </Panel>
    </>
  );
}

/* ─────────── Security ─────────── */

function browserLabel() {
  const ua = navigator.userAgent;
  const browser = /Edg\//.test(ua) ? "Edge" : /Chrome\//.test(ua) ? "Chrome" : /Firefox\//.test(ua) ? "Firefox" : /Safari\//.test(ua) ? "Safari" : "Browser";
  const os = /Windows/.test(ua) ? "Windows" : /Mac OS/.test(ua) ? "macOS" : /Android/.test(ua) ? "Android" : /iPhone|iPad/.test(ua) ? "iOS" : /Linux/.test(ua) ? "Linux" : "Unknown OS";
  return `${browser} on ${os}`;
}

export function SecurityPage() {
  const { data, can, navigate } = useAdmin();
  if (!can("security.view")) return <Forbidden permission="security.view" />;
  const s = data.settings;
  const events = data.activity.filter((a) => ["Roles", "Administrators", "Security", "Settings"].includes(a.module)).slice(0, 8);
  const controls = [
    { icon: KeyRound, label: "Password policy", value: `Minimum ${s.minPasswordLength} characters`, status: "Configured" },
    { icon: ShieldCheck, label: "Two-factor authentication", value: s.require2fa ? "Required for administrators" : "Optional", status: s.require2fa ? "Configured" : "Not required" },
    { icon: Timer, label: "Session timeout", value: `${s.sessionTimeout} minutes of inactivity`, status: "Configured" },
    { icon: LogIn, label: "Public registration", value: s.allowRegistration ? "Enabled" : "Disabled", status: s.allowRegistration ? "Enabled" : "Disabled" },
  ];
  return (
    <>
      <PageHeader eyebrow="System" title="Security" description="Access, sessions and security-relevant events. Policies below are configuration — they take effect once an authentication backend enforces them."
        breadcrumbs={[{ label: "Overview", to: "/admin" }, { label: "Security" }]}
        actions={can("settings.view") && <Button icon={KeyRound} onClick={() => navigate("/admin/settings")}>Edit policies</Button>} />
      <div className="mb-4 flex items-start gap-3 rounded-xl border border-amber-200/20 bg-amber-200/[0.04] p-4 text-sm">
        <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-100" aria-hidden />
        <p className="text-steel"><span className="font-semibold text-snow">No authentication backend is connected.</span> This interface is not protected by a login. Before production, connect an identity provider and enforce every permission on the server.</p>
      </div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {controls.map((c) => (
          <div key={c.label} className="rounded-xl border border-white/[0.07] bg-ink/80 p-4">
            <div className="flex items-center justify-between"><c.icon className="h-4 w-4 text-steel" aria-hidden /><StatusBadge status={c.status} /></div>
            <div className="mt-4 text-sm font-semibold">{c.label}</div>
            <div className="mt-0.5 text-xs text-steel">{c.value}</div>
          </div>
        ))}
      </div>
      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <Panel title="Active sessions" description="Sessions are listed by the authentication backend.">
          <div className="flex items-center gap-3 rounded-lg border border-white/[0.07] bg-obsidian/40 p-3">
            <Monitor className="h-5 w-5 text-steel" aria-hidden />
            <div className="flex-1"><div className="text-sm font-semibold">{browserLabel()}</div><div className="text-xs text-steel">This browser · unauthenticated demo session</div></div>
            <StatusBadge status="Current" />
          </div>
          <p className="mt-3 text-[11px] text-steel">Remote session revocation requires server-side sessions.</p>
        </Panel>
        <Panel title="Login activity">
          <EmptyState icon={LogIn} title="No login activity recorded." description="Sign-in attempts, successes and failures will appear once authentication is connected." />
        </Panel>
        <Panel title="Security events" description="Changes to roles, administrators, settings and security." className="lg:col-span-2">
          {events.length ? (
            <ul className="divide-y divide-white/[0.05]">
              {events.map((e) => (
                <li key={e.id} className="flex flex-col gap-1 py-3 sm:flex-row sm:items-center sm:gap-4">
                  <span className="w-28 font-mono text-[10px] uppercase tracking-[0.12em] text-steel">{e.module}</span>
                  <span className="flex-1 text-sm"><span className="font-semibold">{e.actor}</span> <span className="text-steel">{e.action.toLowerCase()}</span> {e.target}</span>
                  <span className="flex items-center gap-2 text-xs text-steel">{fmtDateTime(e.date)}{e.demo && <DemoTag />}</span>
                </li>
              ))}
            </ul>
          ) : <EmptyState icon={ShieldCheck} title="No security events." />}
        </Panel>
      </div>
    </>
  );
}

/* ─────────── Settings ─────────── */

const settingsTabs = ["General", "Commerce", "Authentication", "Notifications", "Security", "Appearance"];

export function SettingsPage() {
  const { data, mutate, can, toast } = useAdmin();
  const [tab, setTab] = useState("General");
  const [form, setForm] = useState<Settings>(data.settings);
  const [errors, setErrors] = useState<Record<string, string>>({});
  if (!can("settings.view")) return <Forbidden permission="settings.view" />;
  const editable = can("settings.edit");
  const dirty = JSON.stringify(form) !== JSON.stringify(data.settings);
  const set = <K extends keyof Settings>(k: K, v: Settings[K]) => setForm((f) => ({ ...f, [k]: v }));

  const save = () => {
    const e: Record<string, string> = {};
    if (!form.companyName.trim()) e.companyName = "Company name is required.";
    if (form.contactEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.contactEmail)) e.contactEmail = "Enter a valid email address.";
    if (form.taxRate && (isNaN(Number(form.taxRate)) || Number(form.taxRate) < 0 || Number(form.taxRate) > 100)) e.taxRate = "Enter a percentage between 0 and 100.";
    if (form.minPasswordLength < 8) e.minPasswordLength = "Use at least 8 characters.";
    setErrors(e);
    if (Object.keys(e).length) { toast("Review the highlighted settings.", "error"); return; }
    mutate("settings", () => form, { action: "Updated settings", module: "Settings", target: tab });
    toast("Settings saved for this session.");
  };

  return (
    <>
      <PageHeader eyebrow="System" title="Settings" description="Platform configuration for InfiniHon."
        breadcrumbs={[{ label: "Overview", to: "/admin" }, { label: "Settings" }]}
        actions={editable && <><Button variant="ghost" disabled={!dirty} onClick={() => { setForm(data.settings); setErrors({}); }}>Discard</Button><Button variant="primary" icon={Save} disabled={!dirty} onClick={save}>Save changes</Button></>} />
      <Tabs tabs={settingsTabs} value={tab} onChange={setTab} />
      <fieldset disabled={!editable} className="mt-4 max-w-3xl space-y-4">
        {tab === "General" && (
          <Panel title="Company" description="Shown across the site, emails and invoices.">
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Company name" htmlFor="st-name" error={errors.companyName}><input id="st-name" className={inputCls} value={form.companyName} onChange={(e) => set("companyName", e.target.value)} /></Field>
              <Field label="Logo" htmlFor="st-logo" hint="Requires object storage (not configured)."><button id="st-logo" type="button" disabled className={cn(inputCls, "text-left text-steel")}>Upload logo</button></Field>
              <Field label="Contact email" htmlFor="st-email" error={errors.contactEmail}><input id="st-email" type="email" className={inputCls} placeholder="Not set" value={form.contactEmail} onChange={(e) => set("contactEmail", e.target.value)} /></Field>
              <Field label="Contact phone" htmlFor="st-phone"><input id="st-phone" type="tel" className={inputCls} placeholder="Not set" value={form.contactPhone} onChange={(e) => set("contactPhone", e.target.value)} /></Field>
            </div>
          </Panel>
        )}
        {tab === "Commerce" && (
          <Panel title="Commerce">
            <div className="grid gap-4 sm:grid-cols-2">
              <Select hideLabel={false} label="Currency" value={form.currency} onChange={(v) => set("currency", v)} options={[{ value: "", label: "Not set" }, { value: "HNL", label: "HNL — Honduran lempira" }, { value: "USD", label: "USD — US dollar" }]} />
              <Field label="Default tax (%)" htmlFor="st-tax" error={errors.taxRate} hint="Confirm with your accountant before publishing prices."><input id="st-tax" inputMode="decimal" className={inputCls} placeholder="Not set" value={form.taxRate} onChange={(e) => set("taxRate", e.target.value)} /></Field>
            </div>
            <div className="mt-2 divide-y divide-white/[0.05]">
              <Toggle label="Low stock alerts" description="Create a notification when an adjustment drops stock to or below the minimum." checked={form.lowStockAlerts} onChange={(v) => set("lowStockAlerts", v)} disabled={!editable} />
              <Toggle label="Online orders" description="Requires a payment integration." checked={false} onChange={() => undefined} disabled />
            </div>
          </Panel>
        )}
        {tab === "Authentication" && (
          <Panel title="Authentication" description="Enforced by the authentication backend once connected.">
            <div className="divide-y divide-white/[0.05]">
              <Toggle label="Public registration" description="Allow visitors to create customer accounts at /auth/register." checked={form.allowRegistration} onChange={(v) => set("allowRegistration", v)} disabled={!editable} />
              <Toggle label="Login with email and password" description="Identity provider not configured." checked={false} onChange={() => undefined} disabled />
            </div>
            <div className="mt-4 grid gap-4 sm:grid-cols-2">
              <Field label="Minimum password length" htmlFor="st-pw" error={errors.minPasswordLength}><input id="st-pw" type="number" min={8} max={64} className={inputCls} value={form.minPasswordLength} onChange={(e) => set("minPasswordLength", Number(e.target.value))} /></Field>
              <Field label="Session timeout (minutes)" htmlFor="st-sess"><input id="st-sess" type="number" min={5} max={720} className={inputCls} value={form.sessionTimeout} onChange={(e) => set("sessionTimeout", Number(e.target.value))} /></Field>
            </div>
          </Panel>
        )}
        {tab === "Notifications" && (
          <Panel title="Notifications">
            <div className="divide-y divide-white/[0.05]">
              <Toggle label="System notifications" description="Show alerts inside the Control Center." checked={form.systemNotifications} onChange={(v) => set("systemNotifications", v)} disabled={!editable} />
              <Toggle label="Email notifications" description="Requires a transactional email integration (not configured)." checked={form.emailNotifications} onChange={(v) => set("emailNotifications", v)} disabled />
            </div>
          </Panel>
        )}
        {tab === "Security" && (
          <Panel title="Access control">
            <div className="divide-y divide-white/[0.05]">
              <Toggle label="Require two-factor authentication for administrators" checked={form.require2fa} onChange={(v) => set("require2fa", v)} disabled={!editable} />
            </div>
            <p className="mt-3 text-[11px] text-steel">Role permissions are managed in Roles & Permissions. The frontend only hides actions — the backend must reject unauthorized requests.</p>
          </Panel>
        )}
        {tab === "Appearance" && (
          <Panel title="Appearance">
            <div role="radiogroup" aria-label="Theme" className="grid gap-3 sm:grid-cols-2">
              {[{ id: "Obsidian", note: "Default INFINIHON dark theme." }, { id: "Light", note: "Not available yet." }].map((t) => (
                <button key={t.id} type="button" role="radio" aria-checked={form.theme === t.id} disabled={t.id === "Light"} onClick={() => set("theme", t.id)}
                  className={cn("rounded-lg border p-3 text-left disabled:opacity-40", form.theme === t.id ? "border-tech bg-tech/10" : "border-white/10")}>
                  <div className={cn("mb-3 h-14 rounded border border-white/10", t.id === "Obsidian" ? "bg-[linear-gradient(135deg,#05070A,#0A0F14_60%,#003B73)]" : "bg-[#F5F7FA]")} />
                  <div className="text-sm font-semibold">{t.id}</div><div className="text-[11px] text-steel">{t.note}</div>
                </button>
              ))}
            </div>
            <p className="mt-4 text-[11px] text-steel">Branding: INFINIHON · Technology & Infrastructure · Hecho en Honduras.</p>
          </Panel>
        )}
        {!editable && <p className="text-xs text-steel">Read-only: your role cannot edit settings.</p>}
      </fieldset>
    </>
  );
}
